### PR TITLE
Added translations

### LINKED ISSUE #14: Text Localization
Hi,

Is it possible to localise the text so that it supports multiple languages? I have a number of users from non-english speaking countries.

### PR DESCRIPTION
**Pull request by santimar**
Since this library should be used in EU, I added translation for

- Dutch
- French 
- German
- Italian
- Portuguese 
- Spanish 

Translation were provided by @codenia at https://github.com/googleads/googleads-consent-sdk-android/issues/14#issuecomment-396576726
I dropped Chinese, Japanese, Korean, Russian since they are not EU countries.
This should close #14

### CODE REVIEW

**Comment by Johnson145** [comment]
Unfortunately, the translated form files aren't up-to-date anymore. So I can use the English version without a custom provider selection, but it won't work using the other languages. This is because [the latest template changes](https://github.com/googleads/googleads-consent-sdk-android/commit/6503688740bfcb80c48e1713a2d72e5e7e4e73e4#diff-2154ac3babbda0e18205b8261e0043e7) have not yet been applied to the translations.

**Comment by santimar** [comment]
@Johnson145 I added your changes to this PR.
If it ever gets approved...

**Comment by Johnson145** [comment]
Thanks!

I confirm that I'm ok with my commits being contributed to this project.

I don't think this PR will get approved, as it's still a workaround only. In the meantime, it's been really helpful to me though and I'm sure it will be to more people.

**Comment by codenia** [comment]
I also confirm that I'm ok with my translations  being contributed to this project.

**Comment by stowy** [comment]
Just an update that we are aware that this project is not getting the attention it deserves, and we're planning to address that this quarter, hopefully this month. We appreciate your pull requests and encourage you to keep contributing. Be prepared for review in coming weeks, in the meantime please ensure you have signed the CLA and that the CLA check has passed.

**Comment by wharnisch** [comment]
When will we see a new version of the googleads-consent-sdk containing this very important fix ???

**Comment by marco97pa** [comment]
> When will we see a new version of the googleads-consent-sdk containing this very important fix ???

April 2020 and still we haven't got a localized Consent Library

**Pull request closed without merging**
